# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql2
  database: documents_prototype
  host: localhost
  user: root
  password: 
  encoding: utf8
  
production:
  adapter: mysql2
  database: documents_prototype
  host: localhost
  user: root
  password: 
  encoding: utf8
